//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite {
 
 
 public partial class BookingTicket {
 
 /// <summary>
 /// date control.
 /// </summary>
 /// <remarks>
 /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
 /// </remarks>
 protected global::System.Web.UI.HtmlControls.HtmlInputText date;
 
 /// <summary>
 /// userid control.
 /// </summary>
 /// <remarks>
 /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
 /// </remarks>
 protected global::System.Web.UI.HtmlControls.HtmlInputText userid;
 
 /// <summary>
 /// uname control.
 /// </summary>
 /// <remarks>
 /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
 /// </remarks>
 protected global::System.Web.UI.HtmlControls.HtmlInputText uname;
 
 /// <summary>
 /// time control.
 /// </summary>
 /// <remarks>
 /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
 /// </remarks>
 protected global::System.Web.UI.HtmlControls.HtmlInputText time;
 
 /// <summary>
 /// busname control.
 /// </summary>
 /// <remarks>
 /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
 /// </remarks>
 protected global::System.Web.UI.HtmlControls.HtmlInputText busname;
 
 /// <summary>
 /// cost control.
 /// </summary>
 /// <remarks>
 /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
 /// </remarks>
 protected global::System.Web.UI.HtmlControls.HtmlInputText cost;
 
 /// <summary>
 /// from control.
 /// </summary>
 /// <remarks>
 /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
 /// </remarks>
 protected global::System.Web.UI.HtmlControls.HtmlInputText from;
 
 /// <summary>
 /// to control.
 /// </summary>
 /// <remarks>
 /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
 /// </remarks>
 protected global::System.Web.UI.HtmlControls.HtmlInputText to;
 
 /// <summary>
 /// bookingid control.
 /// </summary>
 /// <remarks>
 /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
 /// </remarks>
 protected global::System.Web.UI.HtmlControls.HtmlInputText bookingid;
 
 /// <summary>
 /// noOftickets control.
 /// </summary>
 /// <remarks>
 /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
 /// </remarks>
 protected global::System.Web.UI.HtmlControls.HtmlInputText noOftickets;
 
 /// <summary>
 /// BtnHome control.
 /// </summary>
 /// <remarks>
 /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
 /// </remarks>
 protected global::System.Web.UI.WebControls.Button BtnHome;
 }
}
